In [1]:
import numpy as np
import os
import cv2 as cv
from sklearn.model_selection import train_test_split
import tensorflow as tf
from keras.models import load_model
import pandas as pd

In [ ]:


x = 96
y = 103

modelSynFP = load_model('synFP.h5')

real_data = "SOCOFing/Real"
altered_data = "SOCOFing/Altered"

data = []
labels = []

# load the real data and their labels
photos_names = os.listdir(real_data)
for name in photos_names:
    data.append(cv.imread(os.path.join(real_data ,name) ,cv.IMREAD_GRAYSCALE))
    labels.append(0)

dirs = ["Altered-Easy" ,"Altered-Hard" ,"Altered-Medium"]
for folder in dirs:
    photos_names = os.listdir(os.path.join(altered_data ,folder))
    for name in photos_names:
        data.append(cv.imread(os.path.join(altered_data ,folder ,name) ,cv.IMREAD_GRAYSCALE))
        labels.append(1)

# resizeing all the data to 103X96
for i,image in enumerate(data):
    data[i] = cv.resize(image ,(x,y))

In [ ]:
data = np.stack(data).reshape(-1 ,y ,x ,1)
labels = np.stack(labels).reshape(-1 ,1)

test_data_tensor = tf.convert_to_tensor(data, dtype=tf.float16)
test_labels_tensor = tf.convert_to_tensor(labels, dtype=tf.int16)

# converting to 3 channels
test_data_3 = tf.image.grayscale_to_rgb(test_data_tensor)

In [ ]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

y_pred = modelSynFP.predict(test_data_3)

print("Balanced Accuracy: " +  str(balanced_accuracy_score(test_labels_tensor, np.rint(y_pred))))
print("Confusion Matrix: \n" +  str(confusion_matrix(test_labels_tensor, np.rint(y_pred))))
print(classification_report(test_labels_tensor, np.rint(y_pred)))

1728/1728 [==============================] - 49s 25ms/step
Balanced Accuracy: 0.49978027535349434
Confusion Matrix: 
[[ 5567   433]
 [45736  3534]]
              precision    recall  f1-score   support

           0       0.11      0.93      0.19      6000
           1       0.89      0.07      0.13     49270

    accuracy                           0.16     55270
   macro avg       0.50      0.50      0.16     55270
weighted avg       0.81      0.16      0.14     55270



In [ ]:
a= np.rint(y_pred)

unique, counts = np.unique(a, return_counts=True)

dict(zip(unique, counts))

{0.0: 51303, 1.0: 3967}

In [2]:
modelSoco = load_model('socoF.h5')

In [3]:
x = 96
y = 103

real_data = "SOCOFing/Real"
altered_data = "SOCOFing/Altered"

data = []
labels = []

df = pd.DataFrame(columns=['id', 'image', 'label'])

i = 0
dirs = ["Altered-Easy"]
for folder in dirs:
    photos_names = os.listdir(os.path.join(altered_data ,folder))
    for name in photos_names:
        img = cv.imread(os.path.join(altered_data ,folder ,name) ,cv.IMREAD_GRAYSCALE)
        data.append(img)
        labels.append(1)
        
        df.loc[i, 'id'] = name.split('_')[0]
        df.loc[i, 'image'] = img
        df.loc[i, 'label'] = 1
        i += 1

test_data = df['image'].values
test_labels = df['label'].values

for i,image in enumerate(test_data):
    test_data[i] = cv.resize(image ,(x,y))

test_data = np.stack(test_data).reshape(-1 ,y ,x ,1)
test_labels = np.stack(test_labels).reshape(-1 ,1)

# converting numpy arrays to tensors
test_data_tensor = tf.convert_to_tensor(test_data, dtype=tf.float16)
test_labels_tensor = tf.convert_to_tensor(test_labels, dtype=tf.int16)

# converting to 3 channels
test_data_3 = tf.image.grayscale_to_rgb(test_data_tensor)

In [4]:
# calculate the balanced accuracy
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

y_pred = modelSoco.predict(test_data_3)

print(balanced_accuracy_score(test_labels_tensor, np.rint(y_pred)))
print("Confusion Matrix: \n" +  str(confusion_matrix(test_labels_tensor, np.rint(y_pred))))
print(classification_report(test_labels_tensor, np.rint(y_pred)))

561/561 [==============================] - 19s 26ms/step
0.6618147342591043
Confusion Matrix: 
[[    0     0]
 [ 6064 11867]]
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         0
         1.0       1.00      0.66      0.80     17931

    accuracy                           0.66     17931
   macro avg       0.50      0.33      0.40     17931
weighted avg       1.00      0.66      0.80     17931



c:\Users\Alexandre\anaconda3\envs\tfnn\lib\site-packages\sklearn\metrics\_classification.py:2399: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
c:\Users\Alexandre\anaconda3\envs\tfnn\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Alexandre\anaconda3\envs\tfnn\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Alexandre\anaconda3\envs\tfnn\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-def

In [3]:
x = 96
y = 103

real_data = "SOCOFing/Real"
altered_data = "SOCOFing/Altered"

data = []
labels = []

df = pd.DataFrame(columns=['id', 'image', 'label'])

i = 0
dirs = ["Altered-Medium"]
for folder in dirs:
    photos_names = os.listdir(os.path.join(altered_data ,folder))
    for name in photos_names:
        img = cv.imread(os.path.join(altered_data ,folder ,name) ,cv.IMREAD_GRAYSCALE)
        data.append(img)
        labels.append(1)
        
        df.loc[i, 'id'] = name.split('_')[0]
        df.loc[i, 'image'] = img
        df.loc[i, 'label'] = 1
        i += 1

test_data = df['image'].values
test_labels = df['label'].values

for i,image in enumerate(test_data):
    test_data[i] = cv.resize(image ,(x,y))

test_data = np.stack(test_data).reshape(-1 ,y ,x ,1)
test_labels = np.stack(test_labels).reshape(-1 ,1)

# converting numpy arrays to tensors
test_data_tensor = tf.convert_to_tensor(test_data, dtype=tf.float16)
test_labels_tensor = tf.convert_to_tensor(test_labels, dtype=tf.int16)

# converting to 3 channels
test_data_3 = tf.image.grayscale_to_rgb(test_data_tensor)

In [4]:
# calculate the balanced accuracy
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

y_pred = modelSoco.predict(test_data_3)

print(balanced_accuracy_score(test_labels_tensor, np.rint(y_pred)))
print("Confusion Matrix: \n" +  str(confusion_matrix(test_labels_tensor, np.rint(y_pred))))
print(classification_report(test_labels_tensor, np.rint(y_pred)))

534/534 [==============================] - 17s 26ms/step
0.9634968067029941
Confusion Matrix: 
[[    0     0]
 [  623 16444]]
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         0
         1.0       1.00      0.96      0.98     17067

    accuracy                           0.96     17067
   macro avg       0.50      0.48      0.49     17067
weighted avg       1.00      0.96      0.98     17067



c:\Users\Alexandre\anaconda3\envs\tfnn\lib\site-packages\sklearn\metrics\_classification.py:2399: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
c:\Users\Alexandre\anaconda3\envs\tfnn\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Alexandre\anaconda3\envs\tfnn\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Alexandre\anaconda3\envs\tfnn\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-def

In [3]:
x = 96
y = 103

real_data = "SOCOFing/Real"
altered_data = "SOCOFing/Altered"

data = []
labels = []

df = pd.DataFrame(columns=['id', 'image', 'label'])

i = 0
dirs = ["Altered-Hard"]
for folder in dirs:
    photos_names = os.listdir(os.path.join(altered_data ,folder))
    for name in photos_names:
        img = cv.imread(os.path.join(altered_data ,folder ,name) ,cv.IMREAD_GRAYSCALE)
        data.append(img)
        labels.append(1)
        
        df.loc[i, 'id'] = name.split('_')[0]
        df.loc[i, 'image'] = img
        df.loc[i, 'label'] = 1
        i += 1

test_data = df['image'].values
test_labels = df['label'].values

for i,image in enumerate(test_data):
    test_data[i] = cv.resize(image ,(x,y))

test_data = np.stack(test_data).reshape(-1 ,y ,x ,1)
test_labels = np.stack(test_labels).reshape(-1 ,1)

# converting numpy arrays to tensors
test_data_tensor = tf.convert_to_tensor(test_data, dtype=tf.float16)
test_labels_tensor = tf.convert_to_tensor(test_labels, dtype=tf.int16)

# converting to 3 channels
test_data_3 = tf.image.grayscale_to_rgb(test_data_tensor)

In [4]:
# calculate the balanced accuracy
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

y_pred = modelSoco.predict(test_data_3)

print(balanced_accuracy_score(test_labels_tensor, np.rint(y_pred)))
print("Confusion Matrix: \n" +  str(confusion_matrix(test_labels_tensor, np.rint(y_pred))))
print(classification_report(test_labels_tensor, np.rint(y_pred)))

446/446 [==============================] - 14s 25ms/step
0.9882987668161435
Confusion Matrix: 
[[    0     0]
 [  167 14105]]
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         0
         1.0       1.00      0.99      0.99     14272

    accuracy                           0.99     14272
   macro avg       0.50      0.49      0.50     14272
weighted avg       1.00      0.99      0.99     14272



c:\Users\Alexandre\anaconda3\envs\tfnn\lib\site-packages\sklearn\metrics\_classification.py:2399: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
c:\Users\Alexandre\anaconda3\envs\tfnn\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Alexandre\anaconda3\envs\tfnn\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Alexandre\anaconda3\envs\tfnn\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Recall and F-score are ill-def

In [3]:
x = 96
y = 103

real_data = "SOCOFing/Real"
altered_data = "SOCOFing/Altered"

data = []
labels = []

df = pd.DataFrame(columns=['id', 'image', 'label'])
# load the real data and their labels
photos_names = os.listdir(real_data)

i = 0
for name in photos_names:
    img = cv.imread(os.path.join(real_data ,name) ,cv.IMREAD_GRAYSCALE)
    data.append(img)
    labels.append(0)
    
    df.loc[i, 'id'] = name.split('_')[0]
    df.loc[i, 'image'] = img
    df.loc[i, 'label'] = 0
    i += 1

# load the altered data and their labels
dirs = ["Altered-Easy" ,"Altered-Hard" ,"Altered-Medium"]
for folder in dirs:
    photos_names = os.listdir(os.path.join(altered_data ,folder))
    for name in photos_names:
        img = cv.imread(os.path.join(altered_data ,folder ,name) ,cv.IMREAD_GRAYSCALE)
        data.append(img)
        labels.append(1)
        
        df.loc[i, 'id'] = name.split('_')[0]
        df.loc[i, 'image'] = img
        df.loc[i, 'label'] = 1
        i += 1
        

train, test = train_test_split(df, test_size=0.2, random_state=42, shuffle=True, stratify=df['id'])
# train_data, test_data, train_labels, test_labels  = train_test_split(data, labels, test_size=0.2, random_state=42)

train_data = train['image'].values
train_labels = train['label'].values

test_data = test['image'].values
test_labels = test['label'].values

# resizing all the data to 103X96
# for i,image in enumerate(data):
#     data[i] = cv.resize(image ,(x,y))
    
# data = np.stack(data).reshape(-1 ,y ,x ,1)
# labels = np.stack(labels).reshape(-1 ,1)

# remake the code above for the train and test data
for i,image in enumerate(train_data):
    train_data[i] = cv.resize(image ,(x,y))

train_data = np.stack(train_data).reshape(-1 ,y ,x ,1)
train_labels = np.stack(train_labels).reshape(-1 ,1)

for i,image in enumerate(test_data):
    test_data[i] = cv.resize(image ,(x,y))

test_data = np.stack(test_data).reshape(-1 ,y ,x ,1)
test_labels = np.stack(test_labels).reshape(-1 ,1)


# converting numpy arrays to tensors
train_data_tensor = tf.convert_to_tensor(train_data, dtype=tf.float16)
test_data_tensor = tf.convert_to_tensor(test_data, dtype=tf.float16)
train_labels_tensor = tf.convert_to_tensor(train_labels, dtype=tf.int16)
test_labels_tensor = tf.convert_to_tensor(test_labels, dtype=tf.int16)

# converting to 3 channels
train_data_3 = tf.image.grayscale_to_rgb(train_data_tensor)
test_data_3 = tf.image.grayscale_to_rgb(test_data_tensor)

In [4]:
# calculate the balanced accuracy
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

y_pred = modelSoco.predict(test_data_3)

print(balanced_accuracy_score(test_labels_tensor, np.rint(y_pred)))
print("Confusion Matrix: \n" +  str(confusion_matrix(test_labels_tensor, np.rint(y_pred))))
print(classification_report(test_labels_tensor, np.rint(y_pred)))

346/346 [==============================] - 12s 26ms/step
0.8875934831302199
Confusion Matrix: 
[[1062  148]
 [1009 8835]]
              precision    recall  f1-score   support

           0       0.51      0.88      0.65      1210
           1       0.98      0.90      0.94      9844

    accuracy                           0.90     11054
   macro avg       0.75      0.89      0.79     11054
weighted avg       0.93      0.90      0.91     11054

